### ISSUE TITLE
Dubious TV pairings

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [inker/draw#133]
Hi, thanks for the project, it works really well but you have a problem with your assumption of TV pairings.

Let's look at pairings in previous years.

2018-19:
Real Madrid & Barcelona
Atletico Madrid & Valencia
Bayern Munich & Borussia Dortmund
Manchester City & Tottenham Hotspur
Juventus & Inter
Paris Saint-Germain & Lyon
Lokomotiv Moscow & CSKA Moscow
Porto & Benfica
Manchester United & Liverpool
Napoli & Roma
Schalke 04 & Hoffenheim
Ajax & PSV Eindhoven

2020-21:
Liverpool & Manchester United
Manchester City & Chelsea
Real Madrid & Barcelona
Sevilla & Atletico Madrid
PSG & Olympique Marseille
Bayern & BVB
Leipzig & Borussia M.
Juventus & Inter
Atalanta & Lazio
Zenit & Lokomotiv Moscow
Shakhtar & Dinamo Kiev

You immediately notice one thing: no club is in there twice, and clubs from the same country are split up as much as possible to avoid the situation where 3 clubs from the same country could end up playing on the same day while 1 club from the same country plays on a different day.

Therefore I'm not quite sure about your pairings in https://github.com/inker/draw/blob/master/src/data/pairings.json

**Comment by inker** [comment]
@MarkCiliaVincenti these are the 'backup' pairings that are used in case the real ones are not available. Real pairings been provided since the 2018/19 season. [Example].(https://github.com/inker/draw/blob/master/src/data/cl/gs/2018/pairings.txt).

**Comment by MarkCiliaVincenti** [comment]
Cheers, but what is provisionally being used at the moment please?
