### ISSUE TITLE
Where is the ro16?

### ISSUE THREAD

**Issue by RogerFederer17** [inker/draw#16]
Has it been removed?

**Comment by inker** [comment]
@RogerFederer17, I rewrote the code completely and haven't implemented it, yet. It will be added just after the 6th matchday when both pots are formed.

**Comment by inker** [comment]
@RogerFederer17 [enjoy](https://draw.inker.fun/#/cl/ko). And the [EL](https://draw.inker.fun/#/el/ko), as well.
