### ISSUE TITLE
Support previous format of every European championship,  especially UEFA

### ISSUE THREAD

**Issue by rex9840** [inker/draw#190]
- As i cant create a draw from previous years and previous format of **Champions League**, could you make it so that it support **previous   formats**

**Comment by inker** [comment]
Hi. The previous years are still available (e.g. draw.inker.one/#/cl/gs/2023). I've restored the option to select it in the UI.

**Comment by rex9840** [comment]
https://draw.inker.one/#/undefined/undefined/2023
could you make it  so it redirect to the path you mentioned when used the other options seems like undefined is redirected 

and thank you

**Comment by petrgulman-art** [comment]
Inker, please can you update teams for 2022 and 2026 WC (ALL qualified). And add previous tournaments (2018, 2014 etc.)
