### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Midomaher1** [inker/draw#27]
We need one like that for World Cup 2018 in Russia,Please.

**Comment by matt31pb** [comment]
Yes, it would be fcking awesome. You just need to apply 2 rules there:
A) You can't have more than 2 European teams in one group. 
B) Other confederations (Asia, Africa, North America, South America) can have only one team in group (BTW Australia is Asian in that draw too).

**Comment by inker** [comment]
@Midomaher1, @matt31pb, Is there a detailed description of how the draw will be conducted? Are they going to make it CL-like or resembling EL with the team picked going to the first possible group?

By the way, right now the impatient ones can use [this simulator](http://ultra.zone/2014-FIFA-World-Cup-Group-Stage-Draws).

**Comment by matt31pb** [comment]
@inker Rather EL, teams are just allocated there, where they can be.

**Comment by inker** [comment]
@matt31pb Isn't it what I said? [It also works already](https://draw.inker.fun/#/el), by the way.

**Comment by Midomaher1** [comment]
@inker Yes, It's like EL but the differences are (as before) : 
A) You can't have more than 2 European teams in one group.
B)Other confederations (Asia, Africa, North America, South America) can have only one team in group (BTW Australia is Asian in that draw too).
And there are the 4 pots, and the another simulator is not exciting as yours. 
![download](https://user-images.githubusercontent.com/33672797/32975519-99728eea-cc10-11e7-86d8-c357b934b7bb.jpg)

**Comment by inker** [comment]
@Midomaher1 @matt31pb 

Enjoy - https://draw.inker.fun/#/wc

Please report bugs if you run across any.

**Comment by Midomaher1** [comment]
@inker You are The best,man❤💕💕
