### ISSUE TITLE
How to make this? 

### ISSUE THREAD

**Issue by JackyHuang10** [inker/draw#49]
I really admired that you made one stimulate UEFA Draw lot, and it is really realistic like the real draw lot on the TV. And I want to make one by myself so could you tell me how to make one? 
Many thanks~~ @inker

**Comment by inker** [comment]
@JackyHuang10 Thanks!

I assume by 'make one' you mean making the clone? The tech I've used for this includes:

- [TypeScript](https://www.typescriptlang.org/) (which is a superset of JavaScript)
- [Node.js](https://nodejs.org/en/)
- [Webpack](https://webpack.js.org/)
- [React](https://reactjs.org/)
- and obviously HTML & CSS

**Comment by JackyHuang10** [comment]
@inker Can you make one for me? I still cannot figure out how to do it.
